name: 'Pull request commit summarized'
description: 'Action will summarize all commits in a pull request'
author: 'Deniz Abdurrahmani'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Your Github token'
    required: true

# Define your outputs here.
outputs:
  summary:
    description: 'The commit summary'

runs:
  using: node20
  main: dist/index.js
